# Generated by Django 3.2.8 on 2022-01-12 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fair_sites', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250, verbose_name='full_name')),
                ('logo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='business_logos/', verbose_name='logo')),
                ('logo_ppoi', versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True)),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'owner', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'businesses',
                'ordering': ['full_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_name', models.CharField(max_length=100, verbose_name='short_name')),
                ('is_headquater', models.BooleanField(default=True, verbose_name='is headquater')),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('bonus_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='bonus rate')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_of_sales', to='businesses.business')),
                ('seller', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'seller', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='fair_sites.site')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'ordering': ['short_name', 'created_at'],
            },
        ),
    ]
