# Generated by Django 3.2.4 on 2021-06-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'pays',
                'verbose_name_plural': 'pays',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'quartier',
                'verbose_name_plural': 'quartiers',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair_sites.pays')),
            ],
            options={
                'verbose_name': 'ville',
                'verbose_name_plural': 'villes',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair_sites.ville')),
            ],
            options={
                'verbose_name': 'zone',
                'verbose_name_plural': 'zones',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_code', models.CharField(max_length=50, verbose_name='code du site')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair_sites.quartier')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quartier',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair_sites.zone'),
        ),
    ]
