# Generated by Django 3.2.8 on 2022-02-01 04:32

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='optional_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='static/assets/img/products_pictures/', verbose_name='Optional Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Picture PPOI'),
        ),
    ]
