# Generated by Django 3.2.8 on 2022-02-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220201_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture_ppoi',
        ),
    ]
