# Generated by Django 3.2.8 on 2022-03-12 11:19

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_picture_ppoi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(default='static/assets/img/products_pictures/af-showcase-1.png', upload_to='static/assets/img/products_pictures/', verbose_name='picture of product'),
        ),
    ]
